name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 1.1.1
homepage: https://github.com/bytedance/flutter_ume
publish_to: none

environment:
  sdk: ">=3.3.4"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_ume:
#    path: ../flutter_ume
  flutter_ume:
    git:
      url: https://github.com/May-WDJ/flutter_ume.git
      ref: dev_flutter_3d38d3
  touch_indicator: ^2.0.0

  # for Cyclop
  image: ^4.0.15
  quiver: ^3.2.1
  basics: ">=0.6.0 <0.16.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  lints: ^2.0.0

flutter:
